# Generated by Django 4.1.1 on 2022-10-30 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_remove_student_teachers_remove_student_teacher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
