# Generated by Django 4.1.1 on 2022-10-30 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_student_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teachers',
        ),
    ]
